POST http://localhost:8088/books HTTP/1.1
content-type: application/json

{
    "title": "Golang",
    "author": "TTW"
}
POST http://localhost:8088/books HTTP/1.1
content-type: application/json

{
    "title": "C#",
    "author": "Jack"
}
POST http://localhost:8088/books HTTP/1.1
content-type: application/json

{
    "title": "Java",
    "author": "Sam"
}