// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: todoapi.proto

package todoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoManagerClient is the client API for TodoManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoManagerClient interface {
	// Sends a greeting
	GetTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoReply, error)
	WatchNewTodo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TodoManager_WatchNewTodoClient, error)
}

type todoManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoManagerClient(cc grpc.ClientConnInterface) TodoManagerClient {
	return &todoManagerClient{cc}
}

func (c *todoManagerClient) GetTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoReply, error) {
	out := new(TodoReply)
	err := c.cc.Invoke(ctx, "/todoapi.TodoManager/GetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoManagerClient) WatchNewTodo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TodoManager_WatchNewTodoClient, error) {
	stream, err := c.cc.NewStream(ctx, &TodoManager_ServiceDesc.Streams[0], "/todoapi.TodoManager/WatchNewTodo", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoManagerWatchNewTodoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TodoManager_WatchNewTodoClient interface {
	Recv() (*TodoReply, error)
	grpc.ClientStream
}

type todoManagerWatchNewTodoClient struct {
	grpc.ClientStream
}

func (x *todoManagerWatchNewTodoClient) Recv() (*TodoReply, error) {
	m := new(TodoReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TodoManagerServer is the server API for TodoManager service.
// All implementations must embed UnimplementedTodoManagerServer
// for forward compatibility
type TodoManagerServer interface {
	// Sends a greeting
	GetTodo(context.Context, *TodoRequest) (*TodoReply, error)
	WatchNewTodo(*emptypb.Empty, TodoManager_WatchNewTodoServer) error
	mustEmbedUnimplementedTodoManagerServer()
}

// UnimplementedTodoManagerServer must be embedded to have forward compatible implementations.
type UnimplementedTodoManagerServer struct {
}

func (UnimplementedTodoManagerServer) GetTodo(context.Context, *TodoRequest) (*TodoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodo not implemented")
}
func (UnimplementedTodoManagerServer) WatchNewTodo(*emptypb.Empty, TodoManager_WatchNewTodoServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchNewTodo not implemented")
}
func (UnimplementedTodoManagerServer) mustEmbedUnimplementedTodoManagerServer() {}

// UnsafeTodoManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoManagerServer will
// result in compilation errors.
type UnsafeTodoManagerServer interface {
	mustEmbedUnimplementedTodoManagerServer()
}

func RegisterTodoManagerServer(s grpc.ServiceRegistrar, srv TodoManagerServer) {
	s.RegisterService(&TodoManager_ServiceDesc, srv)
}

func _TodoManager_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoManagerServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todoapi.TodoManager/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoManagerServer).GetTodo(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoManager_WatchNewTodo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoManagerServer).WatchNewTodo(m, &todoManagerWatchNewTodoServer{stream})
}

type TodoManager_WatchNewTodoServer interface {
	Send(*TodoReply) error
	grpc.ServerStream
}

type todoManagerWatchNewTodoServer struct {
	grpc.ServerStream
}

func (x *todoManagerWatchNewTodoServer) Send(m *TodoReply) error {
	return x.ServerStream.SendMsg(m)
}

// TodoManager_ServiceDesc is the grpc.ServiceDesc for TodoManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todoapi.TodoManager",
	HandlerType: (*TodoManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodo",
			Handler:    _TodoManager_GetTodo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNewTodo",
			Handler:       _TodoManager_WatchNewTodo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "todoapi.proto",
}
