// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package models

import (
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

import (
	_ "gorm.io/driver/sqlite"
)

// Injectors from db.go:

func InitDBConnection() (*gorm.DB, error) {
	db, err := newDBConnection()
	if err != nil {
		return nil, err
	}
	return db, nil
}

// db.go:

func newDBConnection() (*gorm.DB, error) {
	var database *gorm.DB
	var err error
	database, err = gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
	if err != nil {
		panic("Failed to connect to database!")
	}

	err = database.AutoMigrate(&Book{})
	if err != nil {
		panic("Failed to migrate to database!")
	}

	return database, nil
}
